######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:50:52 2013
######################################################################

TEMPLATE = app
TARGET = gotocell1
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp

win32: LIBS += -LC:\Qt\Qt5.14.0\5.14.0\msvc2017_64\lib
