######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:39:47 2013
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += hello.cpp

win32: LIBS += -LC:\Qt\Qt5.14.0\5.14.0\msvc2017_64\lib
