######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:52:01 2013
######################################################################

TEMPLATE = app
TARGET = gotocell2
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp

win32: LIBS += -LC:\Qt\Qt5.14.0\5.14.0\msvc2017_64\lib
